build(debug): Fix compile guards and unused variables with WWASSERT, WWDEBUG_SAY, SNAPSHOT_SAY, DEBUG_LOG, assert (#3358)
This fixes 'error C4189: local variable is initialized but not referenced'